---
- name: Install roboto mono nerd font from github
  tags:
    - install_from_gh_releases
  block:
    - name: Ensure ~/.local/share/fonts/ttf/RobotoMono exists
      ansible.builtin.file:
        path: '/home/{{ user }}/.local/share/fonts/ttf/RobotoMono'
        state: directory
        mode: '0755'

    - name: Install roboto mono nerd font from github
      ansible.builtin.unarchive:
        src: 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/RobotoMono.tar.xz'
        dest: '/home/{{ user }}/.local/share/fonts/ttf/RobotoMono'
        remote_src: true
        include: '*.ttf'
        mode: '0644'
