import = ["~/.config/alacritty/themes/tokyonight/tokyonight_night.toml"]

[cursor.style]
shape = "Beam"

[font]
size = 12.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Space", mods = "Control | Shift", action = "None" },
]

[shell]
program = "/bin/bash"
