import = ["~/.config/alacritty/themes/tokyonight/tokyonight_night.toml"]

[window]
padding = { x = 0, y = 0 }
opacity = 0.95

[cursor.style]
shape = "Beam"

[font]
size = 12.0

[font.bold]
family = "RobotoMono Nerd Font Emoji alias"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font Emoji alias"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Emoji alias"
style = "Regular"

[keyboard]
bindings = [
  { key = "Space", mods = "Control | Shift", action = "None" },
]

[shell]
program = "/bin/bash"
