# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$java\
$python\
$line_break\
$jobs\
$character"""

add_newline = true

# Modules by name
aws.disabled = true
azure.disabled = true
battery.disabled = true
buf.disabled = true
bun.disabled = true
c.disabled = true
# character.disabled = true
cmake.disabled = true
cobol.disabled = true
cmd_duration.disabled = true
conda.disabled = true
container.disabled = true
crystal.disabled = true
daml.disabled = true
dart.disabled = true
deno.disabled = true
# directory.disabled = true
direnv.disabled = true
docker_context.disabled = true
dotnet.disabled = true
elixir.disabled = true
elm.disabled = true
env_var.disabled = true
erlang.disabled = true
fennel.disabled = true
fill.disabled = true
fossil_branch.disabled = true
fossil_metrics.disabled = true
gcloud.disabled = true
# git_branch.disabled = true
# git_commit.disabled = true
# git_state.disabled = true
git_metrics.disabled = true
# git_status.disabled = true
# golang.disabled = true
guix_shell.disabled = true
gradle.disabled = true
haskell.disabled = true
haxe.disabled = true
helm.disabled = true
hostname.disabled = true
# java.disabled = true
# jobs.disabled = true
julia.disabled = true
kotlin.disabled = true
kubernetes.disabled = true
# line_break.disabled = true
localip.disabled = true
lua.disabled = true
memory_usage.disabled = true
meson.disabled = true
hg_branch.disabled = true
nim.disabled = true
nix_shell.disabled = true
nodejs.disabled = true
ocaml.disabled = true
opa.disabled = true
openstack.disabled = true
os.disabled = true
package.disabled = true
perl.disabled = true
php.disabled = true
pijul_channel.disabled = true
pulumi.disabled = true
purescript.disabled = true
# python.disabled = true
rlang.disabled = true
raku.disabled = true
red.disabled = true
ruby.disabled = true
rust.disabled = true
scala.disabled = true
shell.disabled = true
shlvl.disabled = true
singularity.disabled = true
solidity.disabled = true
spack.disabled = true
status.disabled = true
sudo.disabled = true
swift.disabled = true
terraform.disabled = true
time.disabled = true
typst.disabled = true
username.disabled = true
vagrant.disabled = true
vlang.disabled = true
vcsh.disabled = true
zig.disabled = true
custom.disabled = true


[golang]
symbol = ' '

[java]
symbol = ' '

[jobs]
symbol = '+'
number_threshold = 1
format = '[\[$number\]$symbol]($style) '

[python]
symbol = ' '
