#!/bin/bash
alias vi='nvim'
alias vim='nvim'
alias ls='\ls -lhF --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias l.='ls -d .* 2>/dev/null' 
alias waybar_restart='pkill waybar; waybar &>/dev/null & disown'
alias klset='brightnessctl -d asus::kbd_backlight set'
alias mlset='brightnessctl -d intel_backlight set'
