---
- name: Disable all shell keymaps
  community.general.dconf:
    key: '/org/gnome/shell/keybindings/{{ item }}'
    value: '[]'
    state: present
  loop:
    - focus-active-notification
    - open-new-window-application-1
    - open-new-window-application-2
    - open-new-window-application-3
    - open-new-window-application-4
    - open-new-window-application-5
    - open-new-window-application-6
    - open-new-window-application-7
    - open-new-window-application-8
    - open-new-window-application-9
    - screenshot
    - screenshot-window
    - shift-overview-down
    - shift-overview-up
    - show-screen-recording-ui
    - show-screenshot-ui
    - switch-to-application-1
    - switch-to-application-2
    - switch-to-application-3
    - switch-to-application-4
    - switch-to-application-5
    - switch-to-application-6
    - switch-to-application-7
    - switch-to-application-8
    - switch-to-application-9
    - toggle-application-view
    - toggle-message-tray
    - toggle-overview
    - toggle-quick-settings

- name: Disable all wm keymaps
  community.general.dconf:
    key: '/org/gnome/desktop/wm/keybindings/{{ item }}'
    value: '[]'
    state: present
  loop:
    - activate-window-menu
    - always-on-top
    - begin-move
    - begin-resize
    - close
    - cycle-group
    - cycle-group-backward
    - cycle-panels
    - cycle-panels-backward
    - cycle-windows
    - cycle-windows-backward
    - lower
    - maximize
    - maximize-horizontally
    - maximize-vertically
    - minimize
    - move-to-center
    - move-to-corner-ne
    - move-to-corner-nw
    - move-to-corner-se
    - move-to-corner-sw
    - move-to-monitor-down
    - move-to-monitor-left
    - move-to-monitor-right
    - move-to-monitor-up
    - move-to-side-e
    - move-to-side-n
    - move-to-side-s
    - move-to-side-w
    - move-to-workspace-1
    - move-to-workspace-10
    - move-to-workspace-11
    - move-to-workspace-12
    - move-to-workspace-2
    - move-to-workspace-3
    - move-to-workspace-4
    - move-to-workspace-5
    - move-to-workspace-6
    - move-to-workspace-7
    - move-to-workspace-8
    - move-to-workspace-9
    - move-to-workspace-down
    - move-to-workspace-last
    - move-to-workspace-left
    - move-to-workspace-right
    - move-to-workspace-up
    - panel-main-menu
    - panel-run-dialog
    - raise
    - raise-or-lower
    - set-spew-mark
    - show-desktop
    - switch-applications
    - switch-applications-backward
    - switch-group
    - switch-group-backward
    - switch-input-source
    - switch-input-source-backward
    - switch-panels
    - switch-panels-backward
    - switch-to-workspace-1
    - switch-to-workspace-10
    - switch-to-workspace-11
    - switch-to-workspace-12
    - switch-to-workspace-2
    - switch-to-workspace-3
    - switch-to-workspace-4
    - switch-to-workspace-5
    - switch-to-workspace-6
    - switch-to-workspace-7
    - switch-to-workspace-8
    - switch-to-workspace-9
    - switch-to-workspace-down
    - switch-to-workspace-last
    - switch-to-workspace-left
    - switch-to-workspace-right
    - switch-to-workspace-up
    - switch-windows
    - switch-windows-backward
    - toggle-above
    - toggle-fullscreen
    - toggle-maximized
    - toggle-on-all-workspaces
    - unmaximize
     
- name: Map keys for moving a window a workspace 
  community.general.dconf:
    key: '/org/gnome/desktop/wm/keybindings/move-to-workspace-{{ item }}'
    value: "['<Super><Shift>{{ item }}']"
    state: present
  loop: '{{ range(1,10,1) | list }}'
  
- name: Map keys for switching to a workspace 
  community.general.dconf:
    key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item }}'
    value: "['<Super>{{ item }}']"
    state: present
  loop: '{{ range(1,10,1) | list }}'

- name: Map keys to interact with windows
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
  loop: 
    - key: /org/gnome/desktop/wm/keybindings/cycle-windows
      value: "['<Alt>Escape']"
    - key: /org/gnome/desktop/wm/keybindings/cycle-windows-backward
      value: "['<Shift><Alt>Escape']"
    - key: /org/gnome/shell/keybindings/show-screenshot-ui
      value: "['Print']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/control-center
      value: "['<Super>i']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/home 
      value: "['<Super>e']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/search 
      value: "['<Super>d']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/www 
      value: "['<Super>a']"
