---
- name: Install github cli
  become: true
  ansible.builtin.dnf:
    name: gh
    state: latest

- name: Install lazygit from github
  block:
    - name: Ensure ~/.local/bin/ exists
      ansible.builtin.file:
        path: '{{ local_bin_path }}'
        state: directory
        mode: '0755'

    - name: Install lazygit from github
      ansible.builtin.unarchive:
        src: "{{ lookup('url', 'https://api.github.com/repos/jesseduffield/lazygit/releases/latest', split_lines=false) | regex_search('browser_download_url.*(https://(.*?)_Linux_x86_64.tar.gz)', '\\1') | first }}"
        dest: '{{ local_bin_path }}'
        remote_src: true
        include: 'lazygit'
        mode: 0755

