---
- name: Install github cli
  ansible.builtin.include_task: install_github_cli

- name: Ensure a basic .gitconfig is present 
  ansible.builtin.include_task: install_gitconfig

- name: Install lazygit
  ansible.builtin.include_task: install_lazygit
