---
- name: Ensure ~/.config/nvim/ exists
  ansible.builtin.file:
    path: '/home/{{ user }}/.config/nvim'
    state: directory
    mode: '0755'

- name: Install neovim configuration
  ansible.builtin.git:
    repo: '{{ neovim_config_repo }}'
    dest: '/home/{{ user }}/.config/nvim'

- name: Install neovim (Fedora)
  tags:
    - install_or_update_software
  when: ansible_distribution | lower == 'fedora'
  become: true
  ansible.builtin.dnf:
    name: 
      - g++
      - cmake
      - ripgrep
      - fd-find
      - fzf
      - neovim
    state: latest
